### ISSUE TITLE
Addition Suggestions

### ISSUE THREAD

**Issue by YnwLNE** [xamionex/CosmeticsMegapack#1]
SillyCosmetics, Zorums Halo ODST Cosmetics, and SoloCosmetics

been waiting for a bundle like this btw so tyvm

**Comment by xamionex** [comment]
> SillyCosmetics, Zorums Halo ODST Cosmetics, and SoloCosmetics
> 
> been waiting for a bundle like this btw so tyvm

Will add after I wake up (in like 3-4h)

ty, show the original creators some love too! ^^

**Comment by YnwLNE** [comment]
> > SillyCosmetics, Zorums Halo ODST Cosmetics, and SoloCosmetics
> > been waiting for a bundle like this btw so tyvm
> 
> Will add after I wake up (in like 3-4h)
> 
> ty, show the original creators some love too! ^^

yeye I do already for my non AC pack but been making a separate AC focused one, Thank you though, cheers!

**Comment by xamionex** [comment]
> yeye I do already for my non AC pack but been making a separate AC focused one, Thank you though, cheers!

^^

Added what you wanted, btw SillyCosmetics was already in there, anyway, there's a [pre-cached version of the mod if you dont want to wait :)](https://thunderstore.io/c/lethal-company/p/amione/CosmeticMegapackWithCache/)

**Comment by YnwLNE** [comment]
guessing it got nuked for being a reupload technically?

**Comment by xamionex** [comment]
> guessing it got nuked for being a reupload technically?

I'm not sure, it says this:
![image](https://github.com/xamionex/CosmeticsMegapack/assets/57235791/dcd471a5-2d65-41f4-9e9d-1ffdf36abd36)
No idea if it was auto or manual, if it's manual I guess that sucks

Gonna reach out to mythic since I've talked to him b4

**Comment by YnwLNE** [comment]
> > guessing it got nuked for being a reupload technically?
> 
> I'm not sure, it says this: ![image](https://private-user-images.githubusercontent.com/57235791/295490569-dcd471a5-2d65-41f4-9e9d-1ffdf36abd36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NzM2MTYsIm5iZiI6MTcwNDg3MzMxNiwicGF0aCI6Ii81NzIzNTc5MS8yOTU0OTA1NjktZGNkNDcxYTUtMmQ2NS00MWY0LTllOWQtMWZmZGYzNmFiZDM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA3NTUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MTg3NGUzNzY5ZGI0MmQzMTRmNmNkNWJjMDM3YTdhYzkyNTY1MzA2NGQ5Y2I0ZGY1ZDkxNjg0NjM5ODZjYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2Ks_DuVCSTZ8C6uI22l1WtEV9O_YhUowsKv-Q_SddMw) No idea if it was auto or manual, if it's manual I guess that sucks
> 
> Gonna reach out to mythic since I've talked to him b4

strange. it should be allowed because technically it's defined as a modpack, which are allowed and don't usually need permission. I'm guessing it's manual because of the reason stated. If it's not allowed then that sucks cause it really is a helpful in avoiding morecompany and also reducing the amount of mods in a modpack. I noticed it was gone when going to report that some of the cosmetics are now missing (I.E equipment company arm cosmetic) lol

**Comment by xamionex** [comment]
> strange. it should be allowed because technically it's defined as a modpack, which are allowed and don't usually need permission. I'm guessing it's manual because of the reason stated. If it's not allowed then that sucks cause it really is a helpful in avoiding morecompany and also reducing the amount of mods in a modpack. I noticed it was gone when going to report that some of the cosmetics are now missing (I.E equipment company arm cosmetic) lol

It was manual, also I didn't notice but apparently AdvancedCompany disables MC at runtime
